# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'webdrivers'
describe 'Bai1' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do

  end
  it 'bai1' do
    @driver.get('http://practice.automationtesting.in/')
    @driver.close
  end
end
