# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'webdrivers'
describe 'Alo' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    
  end
  it 'alo' do
    @driver.get('http://practice.automationtesting.in/')
    @driver.manage.window.resize_to(889, 694)
    @driver.close
  end
end
