# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'webdrivers'
describe 'Alo' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
   
  end
  it 'alo' do
    @driver.get('http://practice.automationtesting.in/')
    @driver.manage.window.maximize
    expect(@driver.title).to eq('Automation Practice Site')
    puts "Tieu de trang web : #{@driver.title}"
    @driver.close
  end
end
