# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require "webdrivers"
describe 'Sd' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
  end
  it 'sd' do
    @driver.get('http://practice.automationtesting.in/')
    @driver.manage.window.resize_to(1056, 696)
    puts " #{@driver.page_source}"
    @driver.close
  end
end
