# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'webdrivers'
describe 'Halo' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
  end
  it 'halo' do
    @driver.get('http://practice.automationtesting.in/')
    @driver.manage.window.resize_to(1056, 698)
    @driver.find_element(:link_text, 'My Account').click
    @driver.find_element(:id, 'reg_email').click
    @driver.find_element(:id, 'reg_email').send_keys('sgophx@gmail.com')
    @driver.find_element(:id, 'reg_password').send_keys('danteancailone')
    @driver.find_element(:name, 'register').click
    @driver.close
  end
end
