# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'webdrivers'
describe 'Halohalo' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
  end
  it 'halohalo' do
    @driver.get('https://the-internet.herokuapp.com/')
    @driver.manage.window.resize_to(550, 699)
    @driver.find_element(:link_text, 'Form Authentication').click
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('tomsmith')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('SuperSecretPassword!')
    @driver.find_element(:css, '.fa').click
    expect(@driver.title).to eq('The Internet')
    puts "Tieu de trang: #{@driver.title}"
    @driver.close
  end
end
