# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'webdrivers'
describe 'Ako' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
  end
  it 'ako' do
    @driver.get('https://itmscoaching.herokuapp.com/form')
    @driver.manage.window.resize_to(550, 700)
    @driver.find_element(:id, 'first-name').click
    @driver.find_element(:id, 'first-name').send_keys('Binh')
    @driver.find_element(:id, 'last-name').click
    @driver.find_element(:id, 'last-name').send_keys('Nguyen')
    @driver.find_element(:id, 'job-title').click
    @driver.find_element(:id, 'job-title').send_keys('Tester')
    @driver.find_element(:css, '.input-group:nth-child(7) > .col-sm-8:nth-child(4)').click
    @driver.find_element(:id, 'radio-button-3').click
    @driver.find_element(:id, 'checkbox-2').click
    @driver.find_element(:id, 'select-menu').click
    dropdown = @driver.find_element(:id, 'select-menu')
    dropdown.find_element(:xpath, "//option[. = '5-9']").click
    @driver.find_element(:css, 'option:nth-child(4)').click
    @driver.find_element(:id, 'datepicker').click
    @driver.find_element(:css, '.datepicker-days .prev').click
    @driver.find_element(:css, 'tr:nth-child(4) > .day:nth-child(4)').click
    @driver.find_element(:link_text, 'Submit').click
    @driver.close
  end
end
